# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    filter_sets:
        cache: ~
        admin_grid_index:
            quality: 75
            filters:
                thumbnail:
                    size: [250, 150]
                    mode: outbound
        baseline_image:
            quality: 75
            filters:
                thumbnail:
                    size: [1280, 855]
                    mode: outbound
        home_event:
            quality: 75
            filters:
                thumbnail:
                    size: [440, 294]
                    mode: outbound
        home_recipe:
            quality: 75
            filters:
                thumbnail:
                    size: [455, 273]
                    mode: outbound
        home_user:
            quality: 75
            filters:
                thumbnail:
                    size: [315, 210]
                    mode: outbound
        recipe_index:
            quality: 75
            filters:
                thumbnail:
                    size: [250, 250]
                    mode: outbound
        event_index:
            quality: 75
            filters:
                thumbnail:
                    size: [270, 188]
                    mode: outbound
        event_content:
            quality: 75
            filters:
                thumbnail:
                    size: [175, 120]
                    mode: outbound
        thumb_author:
            quality: 75
            filters:
                thumbnail:
                    size: [95, 95]
                    mode: outbound
