# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    filter_sets:
        cache: ~
        admin_grid_index:
            quality: 75
            filters:
                thumbnail:
                    size: [250, 150]
                    mode: outbound
        home_event_index:
            quality: 75
            filters:
                thumbnail:
                    size: [440, 294]
                    mode: outbound
        home_recipe_index:
            quality: 75
            filters:
                thumbnail:
                    size: [455, 273]
                    mode: outbound
        recipe_index:
            quality: 75
            filters:
                thumbnail:
                    size: [250, 250]
                    mode: outbound
