vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /media/users
            upload_destination: '%kernel.project_dir%/public/media/users'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        event_image:
            uri_prefix: /media/events
            upload_destination: '%kernel.project_dir%/public/media/events'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        article_image:
            uri_prefix: /media/articles
            upload_destination: '%kernel.project_dir%/public/media/articles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        category_image:
            uri_prefix: /media/categories
            upload_destination: '%kernel.project_dir%/public/media/categories'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        recipe_image:
            uri_prefix: /media/recipes
            upload_destination: '%kernel.project_dir%/public/media/recipes'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
